export const QUAL_PROFISSAO = 'QUAL_PROFISSAO';
export const QUANTO_GANHA_DOLS = 'QUANTO_GANHA_DOLS';
export const ADD_ATIVIDADE = 'ADD_ATIVIDADE';
export const REMOVE_ATIVIDADE = 'REMOVE_ATIVIDADE';
